import React from "react";
import ReactDOM from "react-dom";
import main from './main.css';
const App = () => {
  return (
    <div className="body">
      <p>This is generated by Jsx Files!</p>
    </div>
  );
};
export default App;
ReactDOM.render(<App />, document.getElementById("app"));